mansion = [
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "\t\t\t\t\t\t\t                                               *",
    "\t\t\t\t\t\t\t                                            **   *",
    "\t\t\t\t\t\t\t                                        *   *",
    "\t\t\t\t\t\t\t                                    *   *",
    "\t\t\t\t\t\t\t                                    *  *",
    "\t\t\t\t\t\t\t                      *           *",
    "\t\t\t\t\t\t\t                    *   *           *",
    "\t\t\t\t\t\t\t                  *       *     * * * *",
    "\t\t\t\t\t\t\t                *           *   *     *",
    "\t\t\t\t\t\t\t              *               * *     *",
    "\t\t\t\t\t\t\t            *                   *     *",
    "\t\t\t\t\t\t\t          *                       *   *",
    "\t\t\t\t\t\t\t        *                           * *",
    "\t\t\t\t\t\t\t      *                               *",
    "\t\t\t\t\t\t\t    *                                   *",
    "\t\t\t\t\t\t\t    * *** * *** *** *** **** ** **** ** *",
    "\t\t\t\t\t\t\t    *                                   *",
    "\t\t\t\t\t\t\t    *                                   *",
    "\t\t\t\t\t\t\t    *      De Guzman, Jan Aizen P.      *",
    "\t\t\t\t\t\t\t    *     Bachelor of Science in IT     *",
    "\t\t\t\t\t\t\t    *                                   *",
    "\t\t\t\t\t\t\t    *                                   *",
    "\t\t\t\t\t\t\t    * * * * * * * * * * * * * * * * * * *"
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
]

for brickz in mansion:
    print(brickz)